### ISSUE TITLE
-f "[filesize>10M]" gives the error "requested format not available"

### ISSUE THREAD

**Issue by laggingreflex** [fent/node-youtube-dl#68]
I'm trying to get a video with filesize restriction, as is possible with the `-f "[filesize<100M]"` option. But the **node-youtube-dl** always gives the error "requested format not available". 

The standalone command that **node-youtube-dl** runs internally actually does output the JSON

    python "C:\...\node_modules\youtube-dl\bin\youtube-dl" --dump-json -f "[filesize<100M]" http://youtu.be/...

outputs [this JSON](http://pastebin.com/j6t1Ai1c), which most probably does contain the requested format but **node-youtube-dl** still gives that error. 

I'm using it like this in my node app:

    var video = youtubedl.getInfo(url, [ '-f "[filesize<100M]"' ] , function(err, info) { // err : "requested format not available" } );

It works fine otherwise.

PS: Even `-f "[filesize>10M]"` gives the same error.

**Comment by fent** [comment]
The `args` array passed to the child process will be separated by space, so if your args are normally separated by space in your shell, then you would be separating them by putting them in different items in the array.

    ['-f', '[filesize<100M]']

You also don't need to put quotes around it because the literal string value will be passed.

And the reason the example has an arg in it in one string, is because it isn't separated by a space. Some long options allow this.

    ['--max-quality=18']
