### ISSUE TITLE
Unable to download just audio

### ISSUE THREAD

**Issue by Joshua-F** [fent/node-youtube-dl#77]
When running ``youtubedl(url, ['-x'])`` I get back a video file due to #75 and related changes to adding a default for -f/--format if undefined.

-x is an alias of --extract-audio

**Comment by fent** [comment]
Hmm, did this work before that PR? I don't think post-processing options were ever supported, since this module uses the url it gets back from youtube-dl to create a node stream.

There is `ytdl.exec()`[https://github.com/fent/node-youtube-dl/blob/master/lib/youtube-dl.js#L83] which can be used to call youtube-dl however you like. I'll add it to the readme.

**Comment by Joshua-F** [comment]
Yes, before that PR it worked. From just debugging if I comment out the default args added and turn it into the following and it downloaded as a m4a file, which is the correct format I'm wanting(audio only). I believe this could be fixed by making the if statement check to make sure ``-x`` or ``--extract-audio`` are also not defined before setting the defaults to ``-f best``.
```javascript
  if (!args || args.indexOf('-f') < 0 && args.indexOf('--format') < 0 &&
      args.every(function(a) {
        return a.indexOf('--format=') !== 0;
      })) {
    defaultArgs.push('-x'); // changed -f to -x
    //defaultArgs.push('best');
  }
```

**Comment by fent** [comment]
I don't know if all videos have a m4a version, but the reason it worked before was because the m4a files were part of the original available formats from youtube, and they're considered low quality since it's only audio.

Use the `bestaudio` option

https://github.com/rg3/youtube-dl/blob/master/README.md#format-selection

**Comment by Joshua-F** [comment]
That seems correct, using ``['-f', 'bestaudio']`` worked just how I wanted it.
